# Generated by Django 5.0.1 on 2024-05-20 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=99)),
                ('payment', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='common_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='emp_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('work1', models.FileField(upload_to='')),
                ('work2', models.FileField(upload_to='')),
                ('work3', models.FileField(upload_to='')),
                ('work4', models.FileField(upload_to='')),
                ('work5', models.FileField(upload_to='')),
                ('work6', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='employee_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('license', models.FileField(upload_to='')),
                ('photo', models.FileField(upload_to='')),
                ('location', models.CharField(max_length=50)),
                ('specialised_skill', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=99)),
                ('status', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='feedback1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='log_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('messages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name_onbank', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=10)),
                ('card_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_registration')),
            ],
        ),
    ]
