# Generated by Django 5.0.1 on 2024-05-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='Mesage',
        ),
    ]
