# Generated by Django 5.0.1 on 2024-05-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_registration_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user',
            new_name='user_registration',
        ),
    ]
