# Generated by Django 5.0.1 on 2024-05-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_employee_registration_advamound_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_in',
            name='action',
        ),
    ]
