# Generated by Django 5.0.1 on 2024-05-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_log_in_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_gallery',
            name='advAmound',
        ),
        migrations.RemoveField(
            model_name='emp_gallery',
            name='fullamount',
        ),
        migrations.RemoveField(
            model_name='emp_gallery',
            name='specialised_skill',
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='advAmound',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='fullamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='specialised_skill',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
