# Generated by Django 5.0.1 on 2024-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_employee_registration_advamound_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_gallery',
            name='specialised_skill',
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='specialised_skill',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
