# Generated by Django 5.0.1 on 2024-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_emp_gallery_specialised_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_gallery',
            name='advAmound',
        ),
        migrations.RemoveField(
            model_name='emp_gallery',
            name='fullamount',
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='advAmound',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='fullamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
