# Generated by Django 5.0.1 on 2024-05-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_emp_gallery_advamound_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_no',
            new_name='advAmount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='name_onbank',
            new_name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='employee_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
