# Generated by Django 5.0.1 on 2024-05-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_gallery',
            name='work4',
        ),
        migrations.RemoveField(
            model_name='emp_gallery',
            name='work5',
        ),
        migrations.RemoveField(
            model_name='emp_gallery',
            name='work6',
        ),
    ]
