# Generated by Django 5.0.1 on 2024-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_emp_gallery_work4_remove_emp_gallery_work5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='amountdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullamount', models.IntegerField()),
                ('advAmound', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_registration',
            name='advAmound',
        ),
        migrations.RemoveField(
            model_name='employee_registration',
            name='fullamount',
        ),
        migrations.RemoveField(
            model_name='employee_registration',
            name='username',
        ),
    ]
