# Generated by Django 5.0.1 on 2024-05-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_employee_registration_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_registration',
            name='specialised_skill',
        ),
    ]
