# Generated by Django 5.0.1 on 2024-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_employee_registration_specialised_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback1',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
