# Generated by Django 5.0.1 on 2024-05-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_feedback1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
