# Generated by Django 5.0.1 on 2024-05-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_booking_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountdetails',
            name='functions',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
